// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsIblvDZzMOEGpQWDdNtIPPAOb4tpo53E',
    appId: '1:293055731275:web:28a11923bd6d56e0ab1fce',
    messagingSenderId: '293055731275',
    projectId: 'ato-project-b6bf2',
    authDomain: 'ato-project-b6bf2.firebaseapp.com',
    storageBucket: 'ato-project-b6bf2.appspot.com',
    measurementId: 'G-7WTT5TH9WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbMUpX3xJigu-xiRWEqFTdF-NHP-RU7T0',
    appId: '1:293055731275:android:90bce2eb00c78c98ab1fce',
    messagingSenderId: '293055731275',
    projectId: 'ato-project-b6bf2',
    storageBucket: 'ato-project-b6bf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Do2EY0TzCjgCo2_s58qgj0VZiqtFQt0',
    appId: '1:293055731275:ios:1f0d98ae4cce5eb6ab1fce',
    messagingSenderId: '293055731275',
    projectId: 'ato-project-b6bf2',
    storageBucket: 'ato-project-b6bf2.appspot.com',
    iosBundleId: 'com.project.ato',
  );
}
